djangopractice/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('musicapp.urls')),
]

musicapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'musicapp'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = "index" ),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r"^(?P<album_id>[0-9]+)/favorite/$", views.favorite, name="favorite"),
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),
]

musicapp/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    album_title = models.CharField(max_length = 500)
    artist = models.CharField(max_length = 250)
    genre = models.CharField(max_length = 1000)
    album_logo = models.CharField(max_length= 1000)

    def get_abolute_url(self):
        return reverse('musicapp:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=200)
    is_favorite = models.BooleanField(default = False)

    def __str__(self):
        return self.album.artist + "-" + self.song_title

musicapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song
from django.views import generic
from django.http import Http404, HttpResponse
from django.template import loader
from django.views.generic.edit import CreateView

class IndexView(generic.ListView):
    template_name = 'musicapp/index.html'
    context_object_name = 'all_album'
    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DeleteView):
    model = Album
    template_name = 'musicapp/detail.html'

'''
def index(request):
    all_album = Album.objects.all()
    context = {
        'all_album' : all_album,
    }
    return render(request, "musicapp/index.html", context)
'''
#    all_album = Album.objects.all()
#    template = loader.get_template('musicapp/index.html')
#    context = {
#        'all_album' : all_album,
#    }
#    return HttpResponse(template.render(context, request))
'''

def detail(request, album_id):
    try:
        album = Album.objects.get(id = album_id)
    except Album.DoesNotExist:
        raise Http404("틀렸어 병신아")
    context = {
        'album' : album,
    }
    return render(request, "musicapp/detail.html", context)
'''

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


def favorite(request, album_id):
    album = get_object_or_404(Album, pk = album_id)
    try:
        select_song=album.song_set.get(pk = request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request, 'musicapp/detail.html', {
                      'album' : album,
                      'error_message' : "Yiu did not select a valid song."
        })
    else:
        select_song.is_favorite = True
        select_song.save()
    return render(request, 'musicapp/detail.html', {'album':album})

musicapp/templates/musicapp/album_form.html
{% extends 'musicapp/base.html' %}

{% block Title %} Add new album {% endblock %}
{% block Body %}
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'musicapp/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
    </form>
{% endblock %}

musicapp/templates/musicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %}Title{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'musicapp/style.css'%}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed" rel="stylesheet">
    <script src = "http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MusicApp</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="{% block Current_Albums %}{% endblock %}"><a href="#"><span class="glyphicon glyphicon-triangle-right"></span> Albums <span class="sr-only">(current)</span></a></li>
        <li class="{% block Current_Songs %}{% endblock %}"><a href="#">Songs</a></li>
        <li class="{% block addactive %}{% endblock %}"><a href="{% url 'musicapp:album-add'%}">
            <span class="glyphicon glyphicon-plus"></span>&nbsp;Add Albums</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block Body %}
{% endblock %}
</body>
</html>

musicapp/templates/musicapp/detail.html
{% extends 'musicapp/base.html' %}

{% block Title %} 앨범정보 {% endblock %}
{% block Current_Songs %}active{% endblock %}
{% block Body %}
    <img src="{{ album.album_logo }}" height="200" width="200">
    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>
    <form action ="{% url 'musicapp:favorite' album.id %}" method="post">
        {% csrf_token %}
        {% if error_message %}
            <h3>{{ error_message }}</h3>
        {% endif %}
         {% for song in album.song_set.all %}
             <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
             <label for="song{{ forloop.counter }}">{{ song.song_title }}.{{ song.file_type }}
                {% if song.is_favorite %}
                    <img src="http://i.imgur.com/b9b13Rd.png">
                {% endif %}
             </label><br>
         {% endfor %}
        <br>
        <button type="submit" value="Favorite">Favorite</button>
    </form>
{% endblock %}

musicapp/templates/musicapp/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-2">{{ field }}</div>
    </div>
{% endfor %}

musicapp/templates/musicapp/index.html
{% extends 'musicapp/base.html' %}
{% load staticfiles %}

{% block Title %} 앨범 {% endblock %}
{% block Current_Albums %}active{% endblock %}
{% block Body %}
{% if all_album %}
       <ul>
           {% for album in all_album %}
               <li>
                   <a href = {% url 'musicapp:detail' album.id %}>{{ album.album_title }}</a>
                   <!--<a href = "/music/{{ album.id }}">{{ album.album_title }}</a>-->
               </li>
           {%  endfor %}
       </ul>
{% else %}
       <h1>앨범이 없습니다</h1>
{% endif %}

{% endblock %}